/* eslint-disable */
export const API_DOMAIN = 'https://hvm7nq8v50.execute-api.us-west-2.amazonaws.com/';
export const API_STAGE_NAME = 'dev';
export const FIELD_ERROR_MESSAGE = 'This field is required';
export const QUERY_BULIDER_GUIDANCE_MESSAGE = 'Please customize and run your query in the above window. The search result(s) will be displayed here.';
export const RESULT_SET_EMPTY_MESSAGE = 'Sorry, no records';
export const GET_COMPLETED_WORKBOOKS_COLUMNS = ["USER_ID", "ROLE", "WORKBOOK_ID", "EMPLOYEE_NAME", "WORKBOOK_NAME", "COMPLETED_WORKBOOK", "TOTAL_WORKBOOK", "DUE_DATE", "LAST_ATTEMPT_DATE"];
export const GET_ASSIGNED_WORKBOOKS_COLUMNS = ["USER_ID", "WORKBOOK_ID", "ROLE", "EMPLOYEE_NAME", "WORKBOOK_NAME", "COMPLETED_WORKBOOK", "TOTAL_WORKBOOK", "DUE_DATE"];
export const GET_EMPLOYEES_COLUMNS = ["USER_ID", "SUPERVISOR_ID", "EMPLOYEE_NAME", "ROLE", "ASSIGNED_WORKBOOK", "WORKBOOK_DUE", "PAST_DUE_WORKBOOK", "COMPLETED_WORKBOOK", "TOTAL_EMPLOYEES"];
export const GET_WORKBOOKS_PROGRESS_COLUMNS = ["USER_ID", "WORKBOOK_ID", "TASK_ID", "TASK_CODE", "TASK_NAME", "TOTAL_TASK",  "INCOMPLETE_TASK", "COMPLETED_TASK"];
export const GET_WORKBOOKS_PAST_DUE_COLUMNS = ["USER_ID", "ROLE", "WORKBOOK_ID", "EMPLOYEE_NAME", "WORKBOOK_NAME", "COMPLETED_WORKBOOK", "TOTAL_WORKBOOK", "DUE_DATE"];
export const GET_WORKBOOKS_COMING_DUE_COLUMNS = ["USER_ID", "ROLE", "WORKBOOK_ID", "EMPLOYEE_NAME", "WORKBOOK_NAME", "COMPLETED_WORKBOOK", "TOTAL_WORKBOOK", "DUE_DATE"]
export const GET_WORKBOOKS_REPETITION_COLUMNS = ["NUMBER_OF_ATTEMPTS", "STATUS", "LAST_ATTEMPT_DATE", "LOCATION", "EVALUATOR_NAME", "COMMENTS"]