//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportBuilderAPI.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportBuilderAPI.Resource.DataResource", typeof(DataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKIAJHS5M3WOIIVH4V3A.
        /// </summary>
        internal static string ACCESS_KEY {
            get {
                return ResourceManager.GetString("ACCESS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account doesn’t have login permission.
        /// </summary>
        internal static string ACCOUNT_NOT_HAVING_PERMISSION {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_HAVING_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input!.
        /// </summary>
        internal static string CHECK_INPUT {
            get {
                return ResourceManager.GetString("CHECK_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query has been deleted succcessfully!.
        /// </summary>
        internal static string DELETE_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty name! Please give a Query name to save.
        /// </summary>
        internal static string EMPTY_NAME_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_NAME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string INVALID_CREDENTILAS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTILAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string INVALID_INPUT {
            get {
                return ResourceManager.GetString("INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required.
        /// </summary>
        internal static string PASSWORD_REQ {
            get {
                return ResourceManager.GetString("PASSWORD_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        internal static string PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Name already exist! Please select different one!.
        /// </summary>
        internal static string RENAME_QUERY_ERROR {
            get {
                return ResourceManager.GetString("RENAME_QUERY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query name has been updated successfully!.
        /// </summary>
        internal static string RENAME_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("RENAME_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query has been saved successfully!.
        /// </summary>
        internal static string SAVE_QUERY_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("SAVE_QUERY_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pKsSMLppfeRwNyqLVcPovQYSrfKAr6PvtN/jC1Zd.
        /// </summary>
        internal static string SECRET_KEY {
            get {
                return ResourceManager.GetString("SECRET_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string SERVER_ERROR {
            get {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error.
        /// </summary>
        internal static string SYSTEM_ERROR {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR", resourceCulture);
            }
        }
    }
}
